# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "30 1,4,9 * * 1-5"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - run: echo "$GITHUB_TOKEN"

      # execute the script to retrieve latest BNM exchange rate
      - name: run script
        run: $GITHUB_WORKSPACE/run.sh

      # Runs a single command using the runners shell
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
